### PR TITLE
Authentication and HomePage

### PR DESCRIPTION
**Pull request by 1596aishu**

### CODE REVIEW

**Review by deepakbhimavarapu — COMMENTED** [review]
Aishwarya I hope you didn't implement sessions???

**Comment by 1596aishu** [comment]
No sir, in authentication I didn't use sessions.

**Comment by deepakbhimavarapu** [comment]
You can merge and continue to the next days work.

**Review by deepakbhimavarapu — APPROVED** [review]

**Comment by 1596aishu** [comment]
Ok sir. Thank you

**Pull request merged**
